# Generated by Django 4.2.28 on 2026-06-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical Anomaly')], default='INFO', max_length=20)),
                ('zone', models.CharField(default='General', max_length=100)),
                ('message_en', models.TextField()),
                ('message_yo', models.TextField()),
                ('message_ha', models.TextField()),
                ('message_ig', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('material', models.CharField(choices=[('uPVC', 'Unplasticized PVC'), ('GI', 'Galvanized Iron'), ('HDPE', 'High-Density Polyethylene')], default='uPVC', max_length=20)),
                ('diameter', models.FloatField(default=100.0)),
                ('length', models.FloatField(default=100.0)),
                ('roughness', models.FloatField(default=130.0)),
                ('flow_rate', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('LEAKING', 'Leaking'), ('BURST', 'Burst / Pipe Fracture')], default='NORMAL', max_length=20)),
                ('leak_flow', models.FloatField(default=0.0)),
                ('failure_probability', models.FloatField(default=10.0)),
                ('is_pump', models.BooleanField(default=False)),
                ('pump_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('node_type', models.CharField(choices=[('PUMP', 'Pumping Station'), ('TANK', 'Storage Tank'), ('CONSUMER', 'Consumer Node'), ('JUNCTION', 'Junction/Treatment')], max_length=20)),
                ('elevation', models.FloatField(default=0.0)),
                ('capacity', models.FloatField(default=0.0)),
                ('current_level', models.FloatField(default=0.0)),
                ('base_demand', models.FloatField(default=0.0)),
                ('current_demand', models.FloatField(default=0.0)),
                ('pressure', models.FloatField(default=0.0)),
                ('chlorine', models.FloatField(default=0.0)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tick', models.IntegerField(default=0)),
                ('nepa_status', models.BooleanField(default=True)),
                ('calendar_mode', models.CharField(choices=[('NORMAL', 'Normal Academic Period'), ('EXAMS', 'Exam Period'), ('HOLIDAYS', 'Semester Break/Holidays'), ('ASUU_STRIKE', 'ASUU Strike Outage')], default='NORMAL', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('yo', 'Yoruba (Èdè Yorùbá)'), ('ha', 'Hausa (Harshen Hausa)'), ('ig', 'Igbo (Asụsụ Igbo)')], default='en', max_length=5)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tick', models.IntegerField()),
                ('parameter', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.edge')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.node')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='simulator.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='simulator.node'),
        ),
    ]
